// Generated by `flutterfire configure`.
// This placeholder intentionally contains no credentials.
// Run:
//   flutterfire configure
// to generate the real platform configuration.
class DefaultFirebaseOptions {
  static dynamic get currentPlatform =>
      throw UnimplementedError(
        'Run flutterfire configure to generate lib/firebase_options.dart',
      );
}
